name: internal-tool

services:
  postgres:
    image: postgres
    container_name: internal-tool-postgres
    environment:
      POSTGRES_DB: internal-tool
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - internal-tool_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  internal-tool_postgres_data:
